# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: Resource Group
    azureResourceManagerConnection: 
    subscriptionId: 7551330a-ce82-4dd3-9cf1-d24fdf33d0b9
    action: Create Or Update Resource Group
    resourceGroupName: 
    location: West Europe
    templateLocation: URL of the file
    csmFileLink:
    deploymentMode: Incremental
    deploymentName: DeployPipelineTemplate

